import './globals.css'
import Navbar from './components/navbar/Navbar'
import { Nunito } from 'next/font/google'
import ClientOnly from './components/ClientOnly'
import Modal from './components/modals/Modal'



export const metadata = {
  title: 'Hiens AirBnB clone',
  description: 'Generated by Hien',
}

const font = Nunito({
  subsets: ["latin"]
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <Modal title={"Hiens login"} isOpen={true} />
          <Navbar />
        </ClientOnly>
        {children}</body>
    </html>
  )
}
